### PR TITLE
Fix babel6 issue with @attach

### PR DESCRIPTION
**Pull request by sventschui**
Allows the use of `@attach` when using babel 6 and babel-plugin-transform-decorators-legacy

### CODE REVIEW

**Comment by PillowPillow** [comment]
hi thanks for the pr.

Can you explain me a bit more about the error that occurs when using babel 6? Can you try to update the webpack config with yours in this PR ?

**Comment by sventschui** [comment]
Well we're not using webpack so I can't update with ours ;)

Using babel 6 `@attach` will raise a `TypeError: Unable to delete property`

**Comment by PillowPillow** [comment]
Ok thanks. I ll merge this pr and i ll create a new version tomorrow.
By the way, are you using ng-annotations with a simple task manager like grunt or gulp or an other tool? I ll be glad to know your feedbacks.

**Comment by sventschui** [comment]
Thanks.

We're using gulp/gulp-babel at @axa-ch. I thought about moving to ES6 modules instead of simply concatenating all the files but moving to angular 2 seems to be the better choice if we refactor anything.

**Pull request merged**
