### PR TITLE
Firefox 17 Compatibility

### PR DESCRIPTION
**Pull request by qlaffont**

### CODE REVIEW

**Comment by PillowPillow** [comment]
Hi, thanks for the pr. 
Can you explain me the issue that occurred with firefox 17? I see you only changed the dist file, the fix will not work at the next deployment.

**Comment by qlaffont** [comment]
Hi,
I correct a problem with Firefox 17. With this navigator you have this error : Symbol is not defined.
Best Regards
Quentin

**Comment by PillowPillow** [comment]
Hmm ok, and what did you change to fix that? I can't merge a pull request that only updates the dist file, the issue will come back at the next version..

**Comment by qlaffont** [comment]
This line : 
`return void 0===this.identifiers[e]&&(this.identifiers[e]=typeof Symbol !== 'undefined'?Symbol(e):this.getUUID())`

**Comment by PillowPillow** [comment]
Ok, the v1.0.4 fixed that. Thank's.

**Pull request closed without merging**
